### ISSUE TITLE
Possible violation of Blizzard's EULA

### ISSUE THREAD

**Issue by matjaeck** [cookgreen/OpenSC#2]
Using the assets from the free SC game downloadable from Blizzards BattleNet platform could be a violation of the license limitations explained in C.i (https://www.blizzard.com/de-de/legal/fba4d00f-c7e4-4883-b8b9-1b4500a402ea/blizzard-end-user-license-agreement). 

Are you sure you / your users are not violating the end user license agreement with this project?

**Comment by neuromancer** [comment]
Are the assets included somehow in this repository?

**Comment by matjaeck** [comment]
I don't think so, but this does not negate the problem that a licensee is not allowed to create derivative works with them. The EULA is very strict - I doubt you can safely reverse engineer (it's explicitly prohibited) the game. After all, SC is still active and maintained to run on modern platforms. Sorry to be blunt, but nobody needs a recreation because the game is perfect as it is and still playable. When this becomes playable, it will directly compete with the original game. That's a big difference to the old westwood titles OpenRA and other projects keep alive. I wouldn't care if this wasn't suited to damage OpenRA as a whole.

**Comment by neuromancer** [comment]
> but nobody needs a recreation because the game is perfect as it is and still playable

I can't play it as a native game in Linux or any other open-source operating system, so a recreation is perfectly reasonable for that. There are [a large amount of them](https://osgameclones.com/), in fact, even for "perfect games that are still playable".

**Comment by matjaeck** [comment]
> I can't play it as a native game in Linux or any other open-source operating system

I would also enjoy it if they supported Linux. What I meant was that modern OS/hardware is generally supported - it is possible to play the game on a modern PC with a supported/regularly updated OS. It's up to them to choose which platforms they support. 

A lot of stuff is happening on the webs. I don't know if Blizzard would consider this project a violation of their EULA / reserved rights, but the maintainers should be aware of the risks. I can't contribute any more to the topic and hope they know what they are doing.

**Comment by neuromancer** [comment]
> A lot of stuff is happening on the webs. I don't know if Blizzard would consider this project a violation of their EULA / reserved rights, but the maintainers should be aware of the risks. I can't contribute any more to the topic and hope they know what they are doing.

I think your advise is fair: the maintainers should research this and explain it clearly in the README if they want to continue with this project.

**Comment by yaaaaa** [comment]
We may ask original CD and show original licansie.txt from it every time in mod starts
[License.txt](https://github.com/cookgreen/OpenSC/files/3613385/License.txt)

**Comment by matjaeck** [comment]
> Subject to the Grant of License hereinabove, you may not, in whole or in part, copy, photocopy, reproduce, translate, reverse engineer, derive source 
code, modify, disassemble, decompile, create derivative works based on the Program, or remove any proprietary notices or labels on the Program without the prior consent, in writing, of Blizzard.

**Comment by yaaaaa** [comment]
ok, i refrased easyaly: We really may warning information in any time to project starts: "This project use assets copirated of Blizzard Entertainment, and like a cheat or trainer it potencialy modify original game process, using this project is may lost your licensie of the starcraft game" ?

**Comment by cookgreen** [comment]
> ok, i refrased easyaly: We really may warning information in any time to project starts: "This project use assets copirated of Blizzard Entertainment, and like a cheat or trainer it potencialy modify original game process, using this project is may lost your licensie of the starcraft game" ?

I think we will use the netrual artwork, and I don't think the lost license of starcraft game because we don't use the assets from starcraft game at all?

**Comment by yaaaaa** [comment]
Yes, now we do not use licensied assets
