### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [cookgreen/OpenSC#3]
I think people will be more interested in testing this reimplementation and maybe collaborate with some code if you show its current state with some screenshots (even early ones!).

**Comment by yaaaaa** [comment]
If wee use flipping or fotoshoping SC images, or take Prisma or neural network effects to it, Is this a violation of the license?
![изображение](https://user-images.githubusercontent.com/11130958/64918346-ca577c80-d7be-11e9-999e-c4b691bd9f13.png)

**Comment by yaaaaa** [comment]
https://ppmforums.com/viewtopic.php?p=511123#511123

https://ppmforums.com/viewtopic.php?p=511143#511143

**Comment by yaaaaa** [comment]
![20190915150428181948](https://user-images.githubusercontent.com/11130958/64921295-685d3e00-d7e3-11e9-809a-9a4a3f1c7ad2.jpg)

**Comment by cookgreen** [comment]
done

**Comment by yaaaaa** [comment]
![изображение](https://user-images.githubusercontent.com/11130958/64922570-6c448c80-d7f2-11e9-9b7b-a17dc0bb36be.png)
Something like that
